import { CircuitComponent } from "./types";

export interface CircuitPreset {
  id: string;
  name: string;
  category: string;
  description: string;
  components: CircuitComponent[];
}

export function getPresetCircuits(): CircuitPreset[] {
  return [
    {
      id: "preset-basic-bulb",
      name: "1. Mạch Cơ Bản: Pin - Khóa K - Đèn",
      category: "Nhập môn",
      description: "Mạch điện đơn giản gồm Pin 9V, khóa K, điện trở hạn dòng và bóng đèn dây tóc phát sáng.",
      components: [
        {
          id: "bat-1",
          type: "battery",
          x: 180,
          y: 260,
          rotation: 0,
          terminals: [
            { id: "bat-1-t0", componentId: "bat-1", terminalIndex: 0, x: 140, y: 260, nodeId: "node-0" },
            { id: "bat-1-t1", componentId: "bat-1", terminalIndex: 1, x: 220, y: 260, nodeId: "node-1" },
          ],
          value: 9,
          label: "Nguồn Pin 9V",
          current: 0,
          voltageDrop: 9,
          power: 0,
        },
        {
          id: "sw-1",
          type: "switch",
          x: 320,
          y: 120,
          rotation: 0,
          terminals: [
            { id: "sw-1-t0", componentId: "sw-1", terminalIndex: 0, x: 280, y: 120, nodeId: "node-1" },
            { id: "sw-1-t1", componentId: "sw-1", terminalIndex: 1, x: 360, y: 120, nodeId: "node-2" },
          ],
          value: 0,
          state: true, // Closed
          label: "Khóa K",
          current: 0,
          voltageDrop: 0,
          power: 0,
        },
        {
          id: "bulb-1",
          type: "bulb",
          x: 480,
          y: 200,
          rotation: 90,
          terminals: [
            { id: "bulb-1-t0", componentId: "bulb-1", terminalIndex: 0, x: 480, y: 140, nodeId: "node-2" },
            { id: "bulb-1-t1", componentId: "bulb-1", terminalIndex: 1, x: 480, y: 260, nodeId: "node-0" },
          ],
          value: 15, // 15 Ohm
          label: "Bóng Đèn (15Ω)",
          current: 0,
          voltageDrop: 0,
          power: 0,
        },
        // Wires connecting the loop
        {
          id: "w-bat-sw",
          type: "wire",
          x: 250,
          y: 190,
          rotation: 0,
          terminals: [
            { id: "w-1-t0", componentId: "w-bat-sw", terminalIndex: 0, x: 220, y: 260, nodeId: "node-1" },
            { id: "w-1-t1", componentId: "w-bat-sw", terminalIndex: 1, x: 280, y: 120, nodeId: "node-1" },
          ],
          value: 0,
          label: "Dây nối",
          current: 0,
          voltageDrop: 0,
          power: 0,
        },
        {
          id: "w-sw-bulb",
          type: "wire",
          x: 420,
          y: 130,
          rotation: 0,
          terminals: [
            { id: "w-2-t0", componentId: "w-sw-bulb", terminalIndex: 0, x: 360, y: 120, nodeId: "node-2" },
            { id: "w-2-t1", componentId: "w-sw-bulb", terminalIndex: 1, x: 480, y: 140, nodeId: "node-2" },
          ],
          value: 0,
          label: "Dây nối",
          current: 0,
          voltageDrop: 0,
          power: 0,
        },
        {
          id: "w-bulb-bat",
          type: "wire",
          x: 310,
          y: 260,
          rotation: 0,
          terminals: [
            { id: "w-3-t0", componentId: "w-bulb-bat", terminalIndex: 0, x: 480, y: 260, nodeId: "node-0" },
            { id: "w-3-t1", componentId: "w-bulb-bat", terminalIndex: 1, x: 140, y: 260, nodeId: "node-0" },
          ],
          value: 0,
          label: "Dây nối",
          current: 0,
          voltageDrop: 0,
          power: 0,
        },
      ],
    },
    {
      id: "preset-series-bulbs",
      name: "2. Mạch Nối Tiếp: 2 Bóng Đèn",
      category: "Vật lí 9 & 11",
      description: "Hai bóng đèn mắc nối tiếp. Điện áp nguồn chia đôi (U1 = U2 = 6V), đèn sáng mờ hơn so với mắc đơn lẻ.",
      components: [
        {
          id: "bat-series",
          type: "battery",
          x: 140,
          y: 200,
          rotation: 90,
          terminals: [
            { id: "bs-t0", componentId: "bat-series", terminalIndex: 0, x: 140, y: 260, nodeId: "n-gnd" },
            { id: "bs-t1", componentId: "bat-series", terminalIndex: 1, x: 140, y: 140, nodeId: "n-vcc" },
          ],
          value: 12,
          label: "Pin 12V",
          current: 0,
          voltageDrop: 12,
          power: 0,
        },
        {
          id: "sw-series",
          type: "switch",
          x: 260,
          y: 140,
          rotation: 0,
          terminals: [
            { id: "sws-t0", componentId: "sw-series", terminalIndex: 0, x: 140, y: 140, nodeId: "n-vcc" },
            { id: "sws-t1", componentId: "sw-series", terminalIndex: 1, x: 300, y: 140, nodeId: "n-mid1" },
          ],
          value: 0,
          state: true,
          label: "Khóa K",
          current: 0,
          voltageDrop: 0,
          power: 0,
        },
        {
          id: "bulb-s1",
          type: "bulb",
          x: 390,
          y: 140,
          rotation: 0,
          terminals: [
            { id: "bs1-t0", componentId: "bulb-s1", terminalIndex: 0, x: 300, y: 140, nodeId: "n-mid1" },
            { id: "bs1-t1", componentId: "bulb-s1", terminalIndex: 1, x: 440, y: 140, nodeId: "n-mid2" },
          ],
          value: 10,
          label: "Đèn Đ1 (10Ω)",
          current: 0,
          voltageDrop: 0,
          power: 0,
        },
        {
          id: "bulb-s2",
          type: "bulb",
          x: 520,
          y: 200,
          rotation: 90,
          terminals: [
            { id: "bs2-t0", componentId: "bulb-s2", terminalIndex: 0, x: 440, y: 140, nodeId: "n-mid2" },
            { id: "bs2-t1", componentId: "bulb-s2", terminalIndex: 1, x: 520, y: 260, nodeId: "n-gnd" },
          ],
          value: 10,
          label: "Đèn Đ2 (10Ω)",
          current: 0,
          voltageDrop: 0,
          power: 0,
        },
        {
          id: "w-bottom-series",
          type: "wire",
          x: 330,
          y: 260,
          rotation: 0,
          terminals: [
            { id: "wbs-t0", componentId: "w-bottom-series", terminalIndex: 0, x: 520, y: 260, nodeId: "n-gnd" },
            { id: "wbs-t1", componentId: "w-bottom-series", terminalIndex: 1, x: 140, y: 260, nodeId: "n-gnd" },
          ],
          value: 0,
          label: "Dây về",
          current: 0,
          voltageDrop: 0,
          power: 0,
        },
      ],
    },
    {
      id: "preset-parallel-bulbs",
      name: "3. Mạch Song Song: 2 Bóng Đèn",
      category: "Vật lí 9 & 11",
      description: "Hai bóng đèn mắc song song. Mỗi bóng chịu trọn vẹn 12V nên sáng rực rỡ như nhau. Dòng điện phân nhánh I = I1 + I2.",
      components: [
        {
          id: "bat-par",
          type: "battery",
          x: 120,
          y: 200,
          rotation: 90,
          terminals: [
            { id: "bp-t0", componentId: "bat-par", terminalIndex: 0, x: 120, y: 280, nodeId: "np-gnd" },
            { id: "bp-t1", componentId: "bat-par", terminalIndex: 1, x: 120, y: 120, nodeId: "np-vcc" },
          ],
          value: 12,
          label: "Nguồn 12V",
          current: 0,
          voltageDrop: 12,
          power: 0,
        },
        {
          id: "bulb-p1",
          type: "bulb",
          x: 340,
          y: 200,
          rotation: 90,
          terminals: [
            { id: "bp1-t0", componentId: "bulb-p1", terminalIndex: 0, x: 340, y: 120, nodeId: "np-vcc" },
            { id: "bp1-t1", componentId: "bulb-p1", terminalIndex: 1, x: 340, y: 280, nodeId: "np-gnd" },
          ],
          value: 15,
          label: "Nhánh 1: Đèn Đ1 (15Ω)",
          current: 0,
          voltageDrop: 0,
          power: 0,
        },
        {
          id: "bulb-p2",
          type: "bulb",
          x: 520,
          y: 200,
          rotation: 90,
          terminals: [
            { id: "bp2-t0", componentId: "bulb-p2", terminalIndex: 0, x: 520, y: 120, nodeId: "np-vcc" },
            { id: "bp2-t1", componentId: "bulb-p2", terminalIndex: 1, x: 520, y: 280, nodeId: "np-gnd" },
          ],
          value: 15,
          label: "Nhánh 2: Đèn Đ2 (15Ω)",
          current: 0,
          voltageDrop: 0,
          power: 0,
        },
        {
          id: "w-top-par1",
          type: "wire",
          x: 230,
          y: 120,
          rotation: 0,
          terminals: [
            { id: "wtp1-t0", componentId: "w-top-par1", terminalIndex: 0, x: 120, y: 120, nodeId: "np-vcc" },
            { id: "wtp1-t1", componentId: "w-top-par1", terminalIndex: 1, x: 340, y: 120, nodeId: "np-vcc" },
          ],
          value: 0,
          label: "Dây dương 1",
          current: 0,
          voltageDrop: 0,
          power: 0,
        },
        {
          id: "w-top-par2",
          type: "wire",
          x: 430,
          y: 120,
          rotation: 0,
          terminals: [
            { id: "wtp2-t0", componentId: "w-top-par2", terminalIndex: 0, x: 340, y: 120, nodeId: "np-vcc" },
            { id: "wtp2-t1", componentId: "w-top-par2", terminalIndex: 1, x: 520, y: 120, nodeId: "np-vcc" },
          ],
          value: 0,
          label: "Dây dương 2",
          current: 0,
          voltageDrop: 0,
          power: 0,
        },
        {
          id: "w-bot-par1",
          type: "wire",
          x: 230,
          y: 280,
          rotation: 0,
          terminals: [
            { id: "wbp1-t0", componentId: "w-bot-par1", terminalIndex: 0, x: 120, y: 280, nodeId: "np-gnd" },
            { id: "wbp1-t1", componentId: "w-bot-par1", terminalIndex: 1, x: 340, y: 280, nodeId: "np-gnd" },
          ],
          value: 0,
          label: "Dây âm 1",
          current: 0,
          voltageDrop: 0,
          power: 0,
        },
        {
          id: "w-bot-par2",
          type: "wire",
          x: 430,
          y: 280,
          rotation: 0,
          terminals: [
            { id: "wbp2-t0", componentId: "w-bot-par2", terminalIndex: 0, x: 340, y: 280, nodeId: "np-gnd" },
            { id: "wbp2-t1", componentId: "w-bot-par2", terminalIndex: 1, x: 520, y: 280, nodeId: "np-gnd" },
          ],
          value: 0,
          label: "Dây âm 2",
          current: 0,
          voltageDrop: 0,
          power: 0,
        },
      ],
    },
    {
      id: "preset-dimmer-rheostat",
      name: "4. Mạch Biến Trở Điều Khiển Độ Sáng Đèn",
      category: "Thực hành ứng dụng",
      description: "Dùng biến trở làm điện trở thay đổi để điều chỉnh dòng điện qua đèn, thay đổi độ sáng liên tục từ tối đến sáng rực.",
      components: [
        {
          id: "bat-dim",
          type: "battery",
          x: 140,
          y: 200,
          rotation: 90,
          terminals: [
            { id: "bd-t0", componentId: "bat-dim", terminalIndex: 0, x: 140, y: 270, nodeId: "nd-gnd" },
            { id: "bd-t1", componentId: "bat-dim", terminalIndex: 1, x: 140, y: 130, nodeId: "nd-vcc" },
          ],
          value: 12,
          label: "Nguồn Pin 12V",
          current: 0,
          voltageDrop: 12,
          power: 0,
        },
        {
          id: "pot-1",
          type: "potentiometer",
          x: 300,
          y: 130,
          rotation: 0,
          terminals: [
            { id: "pot-t0", componentId: "pot-1", terminalIndex: 0, x: 140, y: 130, nodeId: "nd-vcc" },
            { id: "pot-t1", componentId: "pot-1", terminalIndex: 1, x: 360, y: 130, nodeId: "nd-mid" },
          ],
          value: 20, // 20 Ohm
          label: "Biến Trở (20Ω)",
          current: 0,
          voltageDrop: 0,
          power: 0,
        },
        {
          id: "bulb-dim",
          type: "bulb",
          x: 480,
          y: 200,
          rotation: 90,
          terminals: [
            { id: "bdim-t0", componentId: "bulb-dim", terminalIndex: 0, x: 360, y: 130, nodeId: "nd-mid" },
            { id: "bdim-t1", componentId: "bulb-dim", terminalIndex: 1, x: 480, y: 270, nodeId: "nd-gnd" },
          ],
          value: 10, // 10 Ohm
          label: "Bóng Đèn (10Ω)",
          current: 0,
          voltageDrop: 0,
          power: 0,
        },
        {
          id: "w-dim-bot",
          type: "wire",
          x: 310,
          y: 270,
          rotation: 0,
          terminals: [
            { id: "wdb-t0", componentId: "w-dim-bot", terminalIndex: 0, x: 480, y: 270, nodeId: "nd-gnd" },
            { id: "wdb-t1", componentId: "w-dim-bot", terminalIndex: 1, x: 140, y: 270, nodeId: "nd-gnd" },
          ],
          value: 0,
          label: "Dây nối",
          current: 0,
          voltageDrop: 0,
          power: 0,
        },
      ],
    },
    {
      id: "preset-fuse-protection",
      name: "5. Mạch Cầu Chì Bảo Vệ Quá Tải",
      category: "An toàn điện",
      description: "Cầu chì chịu tối đa 2.0A. Khi điện trở nhỏ hoặc điện áp quá cao, dòng I > 2A làm nóng chảy đứt cầu chì ngắt mạch bảo vệ.",
      components: [
        {
          id: "bat-fuse",
          type: "battery",
          x: 140,
          y: 200,
          rotation: 90,
          terminals: [
            { id: "bfuse-t0", componentId: "bat-fuse", terminalIndex: 0, x: 140, y: 270, nodeId: "nf-gnd" },
            { id: "bfuse-t1", componentId: "bat-fuse", terminalIndex: 1, x: 140, y: 130, nodeId: "nf-vcc" },
          ],
          value: 12,
          label: "Nguồn 12V",
          current: 0,
          voltageDrop: 12,
          power: 0,
        },
        {
          id: "fuse-1",
          type: "fuse",
          x: 280,
          y: 130,
          rotation: 0,
          terminals: [
            { id: "fuse-t0", componentId: "fuse-1", terminalIndex: 0, x: 140, y: 130, nodeId: "nf-vcc" },
            { id: "fuse-t1", componentId: "fuse-1", terminalIndex: 1, x: 340, y: 130, nodeId: "nf-mid" },
          ],
          value: 2.0, // 2.0 Amperes rating
          state: true, // Intact
          label: "Cầu chì (2.0A)",
          current: 0,
          voltageDrop: 0,
          power: 0,
        },
        {
          id: "res-fuse",
          type: "resistor",
          x: 460,
          y: 200,
          rotation: 90,
          terminals: [
            { id: "rfuse-t0", componentId: "res-fuse", terminalIndex: 0, x: 340, y: 130, nodeId: "nf-mid" },
            { id: "rfuse-t1", componentId: "res-fuse", terminalIndex: 1, x: 460, y: 270, nodeId: "nf-gnd" },
          ],
          value: 8, // 8 Ohm -> I = 12/8 = 1.5A (< 2A, Safe)
          label: "Điện trở tải (8Ω)",
          current: 0,
          voltageDrop: 0,
          power: 0,
        },
        {
          id: "w-fuse-bot",
          type: "wire",
          x: 300,
          y: 270,
          rotation: 0,
          terminals: [
            { id: "wfb-t0", componentId: "w-fuse-bot", terminalIndex: 0, x: 460, y: 270, nodeId: "nf-gnd" },
            { id: "wfb-t1", componentId: "w-fuse-bot", terminalIndex: 1, x: 140, y: 270, nodeId: "nf-gnd" },
          ],
          value: 0,
          label: "Dây nối",
          current: 0,
          voltageDrop: 0,
          power: 0,
        },
      ],
    },
    {
      id: "preset-conductivity-tester",
      name: "6. Thử Nghiệm Tính Dẫn Điện Vật Liệu",
      category: "KHTN 6 & 8",
      description: "Thử nghiệm vật dẫn (đồng xu kim loại cho dòng điện chạy qua làm sáng đèn) so với vật cách điện (cục tẩy cao su làm ngắt mạch).",
      components: [
        {
          id: "bat-test",
          type: "battery",
          x: 140,
          y: 200,
          rotation: 90,
          terminals: [
            { id: "btest-t0", componentId: "bat-test", terminalIndex: 0, x: 140, y: 270, nodeId: "nt-gnd" },
            { id: "btest-t1", componentId: "bat-test", terminalIndex: 1, x: 140, y: 130, nodeId: "nt-vcc" },
          ],
          value: 9,
          label: "Pin 9V",
          current: 0,
          voltageDrop: 9,
          power: 0,
        },
        {
          id: "coin-sample",
          type: "coin",
          x: 290,
          y: 130,
          rotation: 0,
          terminals: [
            { id: "coin-t0", componentId: "coin-sample", terminalIndex: 0, x: 140, y: 130, nodeId: "nt-vcc" },
            { id: "coin-t1", componentId: "coin-sample", terminalIndex: 1, x: 350, y: 130, nodeId: "nt-mid" },
          ],
          value: 0.01,
          label: "Đồng xu kim loại (Vật dẫn)",
          current: 0,
          voltageDrop: 0,
          power: 0,
        },
        {
          id: "bulb-test",
          type: "bulb",
          x: 480,
          y: 200,
          rotation: 90,
          terminals: [
            { id: "btest-t0", componentId: "bulb-test", terminalIndex: 0, x: 350, y: 130, nodeId: "nt-mid" },
            { id: "btest-t1", componentId: "bulb-test", terminalIndex: 1, x: 480, y: 270, nodeId: "nt-gnd" },
          ],
          value: 12,
          label: "Bóng Đèn Kiểm Tra",
          current: 0,
          voltageDrop: 0,
          power: 0,
        },
        {
          id: "w-test-bot",
          type: "wire",
          x: 310,
          y: 270,
          rotation: 0,
          terminals: [
            { id: "wtb-t0", componentId: "w-test-bot", terminalIndex: 0, x: 480, y: 270, nodeId: "nt-gnd" },
            { id: "wtb-t1", componentId: "w-test-bot", terminalIndex: 1, x: 140, y: 270, nodeId: "nt-gnd" },
          ],
          value: 0,
          label: "Dây nối",
          current: 0,
          voltageDrop: 0,
          power: 0,
        },
      ],
    },
  ];
}
